### ISSUE TITLE
刷新页面，没有登录状态，又调回登录界面了

### ISSUE THREAD

**Issue by ohhoney1** [taylorchen709/vueAdmin#16]
如题。什么时候增加保存登录状态的功能，我自己在下面改的时候，用vuex+sessionStorage解决了，但是感觉不完美。期待作者的

**Comment by hjpyh-ybxrz** [comment]
你怎么解决的。。。求教，这个刷新唉

**Comment by ohhoney1** [comment]
@hjpyh-ybxrz 作者最近更新了，你可以参照一下
https://github.com/taylorchen709/vueAdmin/commit/f2cdbdeb3706387a3b980391828fe80a36b703f8

**Comment by hjpyh-ybxrz** [comment]
谢谢了，已经解决了
