### ISSUE TITLE
二级菜单，设置hidden:true 没隐藏

### ISSUE THREAD

**Issue by YYmmlin** [taylorchen709/vueAdmin#18]
![image](https://cloud.githubusercontent.com/assets/12744546/22237828/2882ca80-e249-11e6-8edc-ec8160c2cf13.png)

![image](https://cloud.githubusercontent.com/assets/12744546/22237853/4e386ef6-e249-11e6-846f-d0b8a93d009f.png)

**Comment by YYmmlin** [comment]
解决了

**Comment by hjpyh-ybxrz** [comment]
二级菜单的隐藏需要自己去配置
