### ISSUE TITLE
npm run dev ERROR in ./src/main.js

### ISSUE THREAD

**Issue by sjq597** [taylorchen709/vueAdmin#2]
ERROR in ./src/main.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./components/nav3/Page6.vue in xxxxxxx/vueAdmin/src
 @ ./src/main.js 67:13-51
请问这个是什么问题？

**Comment by taylorchen709** [comment]
./components/nav3/Page6.vue，请找到对应的文件，将文件名改成Page6.vue (P大写)

**Comment by venliong** [comment]
建议所有文件名都小写:

> File names must be all lowercase and may include underscores (_) or dashes (-), but no additional punctuation.

https://google.github.io/styleguide/jsguide.html#file-name

**Comment by taylorchen709** [comment]
谢谢你的建议 @venliong

**Comment by sjq597** [comment]
把src/main.js里面引用的vue组件都改成小写了,另外把一个文件夹下的所有文件名都改成小写的shell命令为:
`ls |awk '$0 !~ tolower($0){printf("mv %s %s\n", $0, tolower($0))|"sh"}'`
可以运行了
