### ISSUE TITLE
右上角的loading框

### ISSUE THREAD

**Issue by dengqianyi** [taylorchen709/vueAdmin#20]
你右上角“退出”这里的loading框不知道是在哪里控制的？
我如何控制它呢？
handleCurrentChange 这个函数谁调用的？

更新补充：
现在发现loading框由NProgress.start();和NProgress.stop()控制，请问他们是怎么关联起来的？

**Comment by taylorchen709** [comment]
这样设置不显示那个loading框：NProgress.configure({ showSpinner: false });
参考https://github.com/rstacruz/nprogress
