### ISSUE TITLE
微信群已超过100人

### ISSUE THREAD

**Issue by njbble** [taylorchen709/vueAdmin#22]
无法通过扫码进入，建议建立一个QQ群

**Comment by hjpyh-ybxrz** [comment]
是啊，wx扫不进去了。。

**Comment by taylorchen709** [comment]
我邀请

**Comment by hjpyh-ybxrz** [comment]
求邀请,wx号:hjpyh-ybxrz

**Comment by hairichuhe** [comment]
能否邀请一下我~，我的qq14320794，我遇到一个报错，Syntax Error: Unexpected token (17:2)

  15 |   computed: {
  16 |  // 使用对象展开运算符将 getters 混入 computed 对象中
> 17 |   ...mapGetters([
     |   ^
  18 |     'getCount'
  19 |     // ...
  20 |   ])
