### ISSUE TITLE
IE9不支持

### ISSUE THREAD

**Issue by cgkoreyoshi** [taylorchen709/vueAdmin#4]
IE9下有脚本错误，如何解决~

**Comment by cgkoreyoshi** [comment]
![9c1a7bb917965a651383df076ca0fd51](https://cloud.githubusercontent.com/assets/14900764/20919977/3bf5dd14-bbd9-11e6-987e-afd5da9891d4.jpg)
请看错误信息  就是直接在IE上访问你的demo网站

**Comment by taylorchen709** [comment]
安装babel-polyfill：npm install babel-polyfill --save-dev
在main.js中引入：import babelpolyfill from 'babel-polyfill'
这个可以解决上面的报错

另外element-ui组件对ie9支持也不好，还是会有些问题，可以尝试更新下版本。
