### ISSUE TITLE
依然抱错

### ISSUE THREAD

**Issue by wwb568109135** [taylorchen709/vueAdmin#7]
[Vue warn]: Error when rendering root instance: warn @ vue.js?1bcd:523Vue._render @ vue.js?1bcd:2961(anonymous function) @ vue.js?1bcd:2191get @ vue.js?1bcd:1656Watcher @ vue.js?1bcd:1648Vue._mount @ vue.js?1bcd:2190Vue$3.$mount @ vue.js?1bcd:5978Vue$3.$mount @ vue.js?1bcd:8305initRender @ vue.js?1bcd:2918Vue._init @ vue.js?1bcd:3296VueComponent @ vue.js?1bcd:3414bind @ element-ui.common.js?e1a0:17986callHook$1 @ vue.js?3de6:4582updateDirectives @ vue.js?3de6:4508invokeCreateHooks @ vue.js?3de6:4093initComponent @ vue.js?3de6:4108createComponent @ vue.js?3de6:4037createElm @ vue.js?3de6:3973createChildren @ vue.js?3de6:4077createElm @ vue.js?3de6:4006patch @ vue.js?3de6:4411Vue._update @ vue.js?3de6:2361(anonymous function) @ vue.js?3de6:2335get @ vue.js?3de6:1643Watcher @ vue.js?3de6:1635Vue._mount @ vue.js?3de6:2334Vue$3.$mount @ vue.js?3de6:5916Vue$3.$mount @ vue.js?3de6:8199init @ vue.js?3de6:2648(anonymous function) @ vue.js?3de6:2802createComponent @ vue.js?3de6:4030createElm @ vue.js?3de6:3973patch @ vue.js?3de6:4411Vue._update @ vue.js?3de6:2361(anonymous function) @ vue.js?3de6:2335get @ vue.js?3de6:1643Watcher @ vue.js?3de6:1635Vue._mount @ vue.js?3de6:2334Vue$3.$mount @ vue.js?3de6:5916Vue$3.$mount @ vue.js?3de6:8199init @ vue.js?3de6:2648createComponent @ vue.js?3de6:4030createElm @ vue.js?3de6:3973createChildren @ vue.js?3de6:4077createElm @ vue.js?3de6:4006patch @ vue.js?3de6:4411Vue._update @ vue.js?3de6:2361(anonymous function) @ vue.js?3de6:2335get @ vue.js?3de6:1643Watcher @ vue.js?3de6:1635Vue._mount @ vue.js?3de6:2334Vue$3.$mount @ vue.js?3de6:5916Vue$3.$mount @ vue.js?3de6:8199init @ vue.js?3de6:2648createComponent @ vue.js?3de6:4030createElm @ vue.js?3de6:3973createChildren @ vue.js?3de6:4077createElm @ vue.js?3de6:4006createChildren @ vue.js?3de6:4077createElm @ vue.js?3de6:4006createChildren @ vue.js?3de6:4077createElm @ vue.js?3de6:4006patch @ vue.js?3de6:4411Vue._update @ vue.js?3de6:2361(anonymous function) @ vue.js?3de6:2335get @ vue.js?3de6:1643Watcher @ vue.js?3de6:1635Vue._mount @ vue.js?3de6:2334Vue$3.$mount @ vue.js?3de6:5916Vue$3.$mount @ vue.js?3de6:8199init @ vue.js?3de6:2648createComponent @ vue.js?3de6:4030createElm @ vue.js?3de6:3973createChildren @ vue.js?3de6:4077createElm @ vue.js?3de6:4006patch @ vue.js?3de6:4411Vue._update @ vue.js?3de6:2361(anonymous function) @ vue.js?3de6:2335get @ vue.js?3de6:1643Watcher @ vue.js?3de6:1635Vue._mount @ vue.js?3de6:2334Vue$3.$mount @ vue.js?3de6:5916Vue$3.$mount @ vue.js?3de6:8199init @ vue.js?3de6:2648createComponent @ vue.js?3de6:4030createElm @ vue.js?3de6:3973patch @ vue.js?3de6:4411Vue._update @ vue.js?3de6:2361(anonymous function) @ vue.js?3de6:2335get @ vue.js?3de6:1643Watcher @ vue.js?3de6:1635Vue._mount @ vue.js?3de6:2334Vue$3.$mount @ vue.js?3de6:5916Vue$3.$mount @ vue.js?3de6:8199init @ vue.js?3de6:2648(anonymous function) @ vue.js?3de6:2802createComponent @ vue.js?3de6:4030createElm @ vue.js?3de6:3973patch @ vue.js?3de6:4448Vue._update @ vue.js?3de6:2368(anonymous function) @ vue.js?3de6:2335get @ vue.js?3de6:1643run @ vue.js?3de6:1712flushSchedulerQueue @ vue.js?3de6:1530(anonymous function) @ vue.js?3de6:465nextTickHandler @ vue.js?3de6:414
vue.js?3de6:427 TypeError: _vm._h is not a function(…)

**Comment by taylorchen709** [comment]
升级一下element-ui
